apiVersion: v1
kind: Secret
metadata:
  name: ca-key-pair
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ .Files.Get "ca.pem" | b64enc | quote }}
  tls.key: {{ .Files.Get "ca-key.pem" | b64enc | quote }}
