imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: DOMAIN.buerokratt.ee # Domain name
secretname:  # Cert name value, change this as suited to environment

ingress:
  certIssuerName: letsencrypt-prod # Change this if your certIssuerName has set up different

release_name: "module-byk-training-gui"
  
images:
  gui:
    registry: "ghcr.io"
    repository: "buerokratt/training-module"
    tag: "pre-alpha-test-1.5.4" # Images (tags) are up to date, currently no changes needed
  dsl:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "training-module-test-1.1.47" # Images (tags) are up to date, currently no changes needed
  pipelines:
    registry: "ghcr.io"
    repository: "buerokratt/training-module"
    tag: "pipeline-PRE-ALPHA-1.3.0" # Images (tags) are up to date, currently no changes needed
    

env:
  REACT_APP_RUUTER_API_URL: "https://ruuter.DOMAIN.buerokratt.ee/v2/private/backoffice" # Change the domain name, leave subdomain and subpath same
  NODE_ENV: "development"
  CHOKIDAR_USEPOLLING: "true"
  REACT_APP_API_URL: "https://ruuter.DOMAIN.buerokratt.ee/v2/private/training" # Change the domain name, leave subdomain and subpath same
  REACT_APP_BUEROKRATT_CHATBOT_URL: "http://byk-bot:5005"
  REACT_APP_OPENSEARCH_DASHBOARD_URL: "https://opensearch.org/"
  REACT_APP_OPENDATAPORT_URL: "https://avaandmed.eesti.ee"
  REACT_APP_RUUTER_V2_PRIVATE_API_URL: "https://ruuter.DOMAIN.buerokratt.ee/v2/private/backoffice" # Change the domain name, leave subdomain and subpath same
  REACT_APP_RUUTER_V2_ANALYTICS_API_URL: "https://ruuter.DOMAIN.buerokratt.ee/v2/private/analytics" # Change the domain name, leave subdomain and subpath same
  REACT_APP_MENU_URL: "https://admin.DOMAIN.buerokratt.ee" # Change the domain name, leave subdomain and subpath same
  REACT_APP_MENU_PATH: "/chat/menu.json"
  REACT_APP_AUTH_BASE_URL: "https://ruuter.DOMAIN.buerokratt.ee/v2/private/backoffice" # Change the domain name, leave subdomain and subpath same
  REACT_APP_APP_PORT: "3001"
  REACT_APP_LOCAL: "false"
  REACT_APP_DOCKER_RUUTER: "http://byk-ruuter-private:8080"
  REACT_APP_CUSTOMER_SERVICE_LOGIN: "http://admin.DOMAIN.buerokratt.ee/et/dev-auth" # Change the domain name, leave subdomain and subpath same
  REACT_APP_CONVERSATIONS_BASE_URL: "https://admin.DOMAIN.buerokratt.ee/chat" # Change the domain name, leave subdomain and subpath same
  REACT_APP_TRAINING_BASE_URL: "https://admin.DOMAIN.buerokratt.ee/training" # Change the domain name, leave subdomain and subpath same
  REACT_APP_ANALYTICS_BASE_URL: "https://admin.DOMAIN.buerokratt.ee/analytics" # Change the domain name, leave subdomain and subpath same
  REACT_APP_SERVICES_BASE_URL: "https://admin.DOMAIN.buerokratt.ee/services" # Change the domain name, leave subdomain and subpath same
  REACT_APP_SETTINGS_BASE_URL: "https://admin.DOMAIN.buerokratt.ee/chat" # Change the domain name, leave subdomain and subpath same
  REACT_APP_MONITORING_BASE_URL: "https://admin.DOMAIN.buerokratt.ee/monitoring" # Change the domain name, leave subdomain and subpath same
  REACT_APP_SERVICE_ID: "training"
  REACT_APP_RUUTER_PRIVATE_API_URL: "https://ruuter.DOMAIN.buerokratt.ee/v2/private/backoffice" # Change the domain name, leave subdomain and subpath same
  REACT_APP_BASE_URL: "byrokratt/"
  REACT_APP_SERVICE_MODULE_GUI_BASE_URL: "https://admin.DOMAIN.buerokratt.ee/services/" # Change the domain name, leave subdomain and subpath same
  REACT_APP_NODE_ENV: "development"
  REACT_APP_RUUTER_URL: "https://ruuter.DOMAIN.buerokratt.ee/v2/private/training/" # Change the domain name, leave subdomain and subpath same
  REACT_APP_RUUTER_URL: "https://ruuter.DOMAIN.buerokratt.ee/v2/private/training/"
  REACT_APP_SERVICE_MODULE_GUI_BASE_URL: "http://module-byk-services-gui:3006"


liquibase:
  jdbcUrl: "jdbc:postgresql://component-databases-users-db:5432/byk?user=byk"    
  dbPassword: "01234"  # Change password accordingly
