apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-training-dsl
spec:
  storageClassName: dsl
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/training-dsl
