{{- if .Values.fluentBit.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.releaseName }}-fluent-bit-config
data:
  fluent-bit.conf: |-
{{ .Files.Get "files/fluent-bit.conf" | indent 4 }}
{{- end -}}
