imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: test.buerokratt.ee # Domain name

#ingress:
#  tlsConfigMapName: byk-tls-configmap

ingress:
  certIssuerName: letsencrypt-prod-issuer

#release_name: "postdeploy"
release_name: "cronjob"

cronenv:
  REPO_URL: https://github.com/buerokratt/buerokratt-helm
  BRANCH: dev
  CHARTS_DIR: # Enter the charts directory
  NAMESPACE: # Enter the correct namespace value