apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.release_name }}"
spec:
  selector:
    app: "{{ .Values.release_name }}"
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: http
    - port: 9600
      targetPort: 9600
      protocol: TCP
      name: opensearch
