apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.release_name }}-config"
data:
  development.env: |
    API_CORS_ORIGIN=*
    API_DOCUMENTATION_ENABLED=false

    S3_REGION=us-east-1
    S3_ENDPOINT_URL=s3.riigipilv.ee:443
    S3_ACCESS_KEY_ID=ria-byk-test
    S3_SECRET_ACCESS_KEY=aP2NlK23P22SUpCreIxCA0hG+SaFPuHiA0eWpMcm
    S3_DATA_BUCKET_NAME=test-bucket-01
    S3_DATA_BUCKET_PATH=

    FS_DATA_DIRECTORY_PATH=./data
