apiVersion: v1
kind: Secret
metadata:
  name: byk-tim-env-secret
type: Opaque
data:
  oauth2_client_secret: {{ .Values.byk.tim.env.security.oauth2.client.clientSecret | b64enc }}
  jwt_integration_key_store_password: {{ .Values.byk.tim.env.jwtIntegration.signature.keyStorePassword | b64enc }}
  password: {{ .Values.tim_postgresql | b64enc }}