apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.release_name }}"
spec:
  selector:
    app: "{{ .Values.release_name }}"
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http