imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: DOMAIN.buerokratt.ee # Domain name
secretname: # Cert name value, change this as suited to environment

ingress:
  certIssuerName: letsencrypt-prod # Change this if your certIssuerName has set up different

release_name: "module-byk-widget"

images:
  gui:
    registry: "ghcr.io"
    repository: "buerokratt/chat-widget"
    tag: "pre-alpha-test-1.1.5" # Images (tags) are up to date, currently no changes needed
  dsl:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "pre-alpha-1.3.2"  # Images (tags) are up to date, currently no changes needed

config: 
  header_origin: "https://DOMAIN.buerokratt.ee" # Change the domain name, leave subdomain and subpath same
