apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.release_name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.release_name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.release_name }}"
    spec:
      initContainers:
        - name: init-copy-files
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /Ruuter/DSL
              cp -r /app/DSL/public/backoffice /root/DSL/
              ls -la /root/
              ls -la /root/DSL/
            
          volumeMounts:
            - name: buerokratt-dsl
              mountPath: /app/DSL/
            - name: ruuter-volume
              mountPath: /root/DSL/
      containers:
        - name: "{{ .Values.release_name }}"
          image: "{{ .Values.images.scope.registry }}/{{ .Values.images.scope.repository }}:{{ .Values.images.scope.tag }}"
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: logging.level.root
              value: "{{ .Values.env.LOGGING_LEVEL_ROOT }}"
            - name: LOG_LEVEL_TIMING
              value: "{{ .Values.env.LOG_LEVEL_TIMING }}"
            - name: application.logging.displayRequestContent
              value: "{{ .Values.env.APPLICATION_LOGGING_DISPLAY_REQUEST_CONTENT }}"
            - name: application.logging_displayResponseContent
              value: "{{ .Values.env.APPLICATION_LOGGING_DISPLAY_RESPONSE_CONTENT }}"
          volumeMounts:
            - name: ruuter-volume
              mountPath: /DSL/
            - name: buerokratt-dsl
              mountPath: /app/ruuter
            - name: urls-env
              mountPath: /app/constants.ini
              subPath: constants.ini
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 13
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: buerokratt-dsl
          persistentVolumeClaim:
            claimName: pvc-buerokratt-dsl
        - name: ruuter-volume
          emptyDir: {}
        - name: urls-env
          configMap:
            name: urls-env-config
