apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-ruuter
spec:
  selector:
    matchLabels:
      app: byk-ruuter
  template:
    metadata:
      labels:
        app: byk-ruuter
    spec:
      initContainers:
        - name: init-copy-files
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p Ruuter/DSL
              echo test.yml
              cp -r /app/DSL/backoffice /root/DSL/
              
              ls -la
          volumeMounts:
            - name: buerokratt-dsl
              mountPath: /app/DSL/
            - name: ruuter-volume
              mountPath: /root/DSL/
      containers:
        - name: byk-ruuter
          image: "{{ .Values.images.scope.registry }}/{{ .Values.images.scope.repository }}:{{ .Values.images.scope.tag }}"
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: logging.level.root
              value: "{{ .Values.env.logging_level_root }}"
            - name: LOG_LEVEL_TIMING
              value: "{{ .Values.env.LOG_LEVEL_TIMING }}"
            - name: application.logging.displayRequestContent
              value: "{{ .Values.env.application_logging_displayRequestContent }}"
            - name: application.logging_displayResponseContent
              value: "{{ .Values.env.application_logging_displayResponseContent }}"
          volumeMounts:
            - name: ruuter-volume
              mountPath: /DSL/
            - name: urls-env
              mountPath: /app/constants.ini
              subPath: constants.ini
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: buerokratt-dsl
          persistentVolumeClaim:
            claimName: pvc-buerokratt-dsl
        - name: ruuter-volume
          emptyDir: {}
        - name: urls-env
          configMap:
            name: urls-env-config
