apiVersion: v1
kind: PersistentVolume
metadata:
  name: dmapper-service-dsl
spec:
  storageClassName: longhorn
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data
