apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-training-dmapper-dsl
spec:
  storageClassName: dsl
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data